name: adaptive_explorations
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.10.0-290.1.beta

dependencies:
  flutter:
    sdk: flutter
  provider: ^6.1.5+1
  shadcn_flutter: ^0.0.46

dev_dependencies:
  flutter_lints: ^6.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
