name: app
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.8.1

dependencies:
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  freezed_annotation: ^3.0.0
  get_it: ^8.0.3
  go_router: ^16.0.0
  http: ^1.4.0
  path_provider: ^2.1.5
  shadcn_flutter: ^0.0.40
  shared_preferences: ^2.5.3

dev_dependencies:
  build_runner: ^2.5.4
  flutter_lints: ^5.0.0
  flutter_test:
    sdk: flutter
  freezed: ^3.0.6

flutter:
  uses-material-design: true

  config:
    enable-swift-package-manager: false
